### ISSUE TITLE
[Feature Request] I want you to bundle makePositionParams to this.

### ISSUE THREAD

**Issue by kuuote** [uga-rosa/deno-denops-lsputil#2]
I want you to bundle makePositionParams to this.
It is internal function of `ddu-source-lsp`.
https://github.com/uga-rosa/ddu-source-lsp/blob/f1d15a479c3a12fba4e9ec7b046657cb7218b761/denops/ddu_source_lsp/params.ts#L15-L26
Still now, import from GitHub is available in deno, but I thought it is versatile function and I want to use it from stable library.

**Comment by uga-rosa** [comment]
Added in v0.6.0
